### ISSUE TITLE
git:from-image ledokku ledokku/ledokku:0.7.0` is not a dokku command.

### ISSUE THREAD

**Issue by baptisteArno** [ledokku/ledokku#405]
When executing `dokku git:from-image ledokku ledokku/ledokku:0.7.0` it says `git:from-image ledokku ledokku/ledokku:0.7.0 is not a dokku command.`

- Version of dokku: 0.23.0

Any ideas?

**Comment by Akirtovskis** [comment]
@baptisteArno Thanks for opening the issue, this is indeed not working because git:from-image was introduced only after dokku version 0.24.0 . If that is possible could you please try running Ledokku with dokku `0.24.10`?  

Here's the 0.24.10 install script : 
```
wget https://raw.githubusercontent.com/dokku/dokku/v0.24.1/bootstrap.sh
sudo DOKKU_TAG=v0.24.1 bash bootstrap.sh
```

There are some issues with the latest Dokku version that we are investigating, but with 0.24.10 it works smoothly.

**Comment by baptisteArno** [comment]
Ok that's what I thought! Thank you for this app 🙌
